#!/bin/sh

[ -d /proc ] || mkdir -p /proc
mount /proc

[ -d /sys ] || mkdir -p /sys
mount /sys

# devtmpfs may automount
[ -d /dev ] || mkdir -p /dev
grep -e "^devtmpfs\s*/dev\s*devtmpfs\s*" /proc/mounts ||
  mount /dev

[ -d /dev/pts ] || mkdir -p /dev/pts
mount /dev/pts

[ -f /etc/hostname ] && hostname -F /etc/hostname

for i in /var/run /media; do
  [ -d "${i}" ] || mkdir -p "${i}"
  mount -t tmpfs -osize=10m none "${i}"
done

mount -t debugfs none /sys/kernel/debug &> /dev/null

[ -e /etc/ld.so.cache ] || ldconfig -C /var/run/ld.so.cache

fw_fallback_ignore_knob=/proc/sys/kernel/firmware_config/ignore_sysfs_fallback
[ -e $fw_fallback_ignore_knob ] && echo "1" > $fw_fallback_ignore_knob

# echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all



source /etc/init.d/start
