#!/bin/sh

. /etc/init.d/func

/etc/init.d/mdev-initd start

cmd_run dmesg -n 4
cmd_run ifconfig lo up 127.0.0.1

for script in `find /etc/init.d -iname S[0-9]*`; do
  [ -x $script ] || continue;
  echo "Start ... $script"
  $script start
done
