#!/bin/sh

. /etc/init.d/func

_pri_tag="mdev-initd"

log_d "$0 $*"

_pri_mdev_exec="/sbin/mdev"
_pri_mdev_log="/var/run/mdev.log"
log_f "$_pri_mdev_log"
log_f "$_pri_mdev_log" "$0 $*"

case "$1" in
start)
  shift
  pgrep -x $_pri_mdev_exec &>/dev/null && { log_d "mdev already running"; exit 0; }
  [ ! -f /etc/mdev.conf ] && { log_d "Miss /etc/mdev.conf "; exit 0; }
  cmd_run eval "$_pri_mdev_exec -d ${_pri_mdev_log:+-f -v &>$_pri_mdev_log &}"
  ;;
stop)
  shift
  _pri_mdev_pid="$(pgrep -x $_pri_mdev_exec)"
  [ -n "$_pri_mdev_pid" ] || exit 0
  log_d "Kill mdev"
  cmd_run eval "kill -9 $_pri_mdev_pid &>/dev/null"
  ;;
restart)
  shift
  $0 stop && $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start|stop|restart]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
