#!/bin/sh

. /sbin/func.sh

check_refactory () {
  [ -f $oob_cfg ] || return 0
  local refact="$(as_num $(get_inient1 $oob_cfg refactory))"
  if [ "$refact" -ge 1 ] &>/dev/null; then
    log_d "set refactory=$(( $refact - 1 ))"
    echo "refactory=$(( $refact - 1 ))" > $oob_cfg
    return
  fi
  cmd_run rm -rf $oob_cfg
}

check_promisc () {
  [ -f $promisc_cfg ] || return 0
  local promisc="$(as_num $(get_inient1 $promisc_cfg promisc))"
  if [ "$promisc" -ge 1 ] &>/dev/null; then
    log_d "set promisc=$(( $promisc - 1 ))"
    echo "promisc=$(( $promisc - 1 ))" > $promisc_cfg
    return
  fi
  cmd_run rm -rf $promisc_cfg
}

check_snhash () {
  [ -f $snhash_cfg ] || return 0
  
  _pri_sn=`$(/sbin/func.sh_test get_inient1 $macaddr_cfg macaddr | sed -e "s/://g")`
  [ -z "$_pri_sn" ] && _pri_sn=`$(/sbin/func.sh_test macaddr_gen)`
  _pri_hash=
}

/etc/init.d/mdev-initd start

cmd_run dmesg -n 4
cmd_run ifconfig lo up 127.0.0.1

# cmd_run /etc/init.d/persist start ||
#   cmd_run /etc/init.d/persist stop

# check_snhash

[ -f "$hostname_cfg" ] || cmd_run cp /etc/hostname-template "$hostname_cfg"
cmd_run admin --hostname -f "$hostname_cfg"

[ -f $wpasup_cfg ] || cmd_run cp /etc/wpa_supplicant-template.conf $wpasup_cfg

# check_refactory
# check_promisc

for script in `find /etc/init.d -iname "S[0-9]*" | sort`; do
  [ -x $script ] || continue;
  log_sd "Starting ... $script"
  $script start
done
