#!/bin/sh

. /sbin/func.sh

_pri_tag="lighttpd-initd"

log_d "$0 $*"

case "$1" in
start)
  pgrep -x ".*lighttpd" &>/dev/null && { log_d "Already running"; exit 0; }
  lighttpd -f /etc/lighttpd.conf &>/dev/null
  ;;
stop)
  pgrep -x ".*lighttpd" &>/dev/null || exit 0
  killall -9 lighttpd &>/dev/null
  exit 0
  ;;
restart)
  shift
  $0 stop && $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
