#!/bin/sh

. /sbin/func.sh

_pri_tag="restmon"

log_d "$0 $*"

log_file=
log_file="/var/run/restmon.log"
log_f "$log_file"
log_f "$log_file" "$0 $*"

case "$1" in
start)
  _pri_cmd="admin --ctrlport=/root/admin-ctrl --restkey=120"
  if [ -f "$led_cfg" ]; then
    _pri_cmd="$_pri_cmd --ledconf=$led_cfg"
  fi
  cmd_run eval "$_pri_cmd ${log_file:+-vvv >>$log_file 2>&1} &"
  exit
  ;;
stop)
  pgrep -x ".*admin" &>/dev/null || exit 0
  killall admin &>/dev/null
  exit
  ;;
restart)
  shift
  $0 stop && $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
esac
